package com.payroll_backend.enums;

public enum AllowanceType {
    TAX_RELIEF, HOUSING, TRANSPORT, MEAL, MEDICAL, EDUCATION, RELOCATION, COMMUNICATION, AIRTIME, UNIFORM, TRAVEL, PERFORMANCE_BASED, OTHER
}
